index.html
public/index.css
views/calendar.html

Add a calendar page to the website (with only basic styling).
Closes #XXXXX

feat: add calendar page

---

public/index.css

Added color codes to `css` file
Closes #10

Added color codes

---

index.html
public/index.css

has a horizontal nav bar for the website as suggested in the issue
Closes #6

added nav bar

---

templates/moderator-card.html

Creating a template for the moderator's "cards" on the community page.
Closes #XXXXX

feat: create mod card template

---

index.html
public/index.css

It would be good to get some feedback on the current information for the landing page
I've some info in the index.html file here https://github.com/Skyhero-admin/homepage
If you have any suggestions to add or if something doesn't seem right and should be removed then please do let me know 😅
Also It's still not styled yet so I need some ideas for it

Added some info to the page

---

index.html

Changed src of the image in index.html on line 74
Closes #20

Updated src of index.html on line 74

---

.github/PULL_REQUEST_TEMPLATE.md

Minor improvements in the pull request template

---

public/index.css

Made the navigation sticky and added padding to the right side of the nav. 
Closes #24

Sticky nav

---

public/index.css

welcome text center

---

.prettierrc
templates/moderator-card.html

Adds a `.prettierrc` file to contain default settings.
Closes #XXXXX

feat: add prettierrc

---

index.html
public/utilities.css

This PR redesigns the moderator card section, updates the moderator's information, and adds our missing team members.
Closes #XXXXX

feat: redesign moderators

---

public/index.css

Welcome box height

---

public/modcard.css

Updated the card styling

---

index.html
public/data/_template.json
public/utilities.css

- Use a placeholder for staff that have not provided info yet.
- Set the `cursor` to `pointer` on the cards.
Closes #XXXXX

feat: use placeholder

---

index.html

I added the chat room link to the [index file](https://github.com/nhcommunity/homepage/blob/235da2703edab21dd5b267561a6486bbed26c80c/index.html#L40).
#27 
Closes #XXXXX

fixed chat room link

---

index.html
public/data/panquesito.json
public/modcard.css

Add @Panquesito7's data.
Closes #XXXXX

feat: panquesito

---

index.html

feat: Add Open Graph Meta tags

---

index.html

- Fixed the Profile Photo link

Update Profile Photo Link

---

public/data/panquesito.json

- Update my profile on the moderation part.

chore: update my profile

---

new/hamburger.css
new/index.html
new/index.js
new/style.css
new/utilities.css

Fix the UI issue in the rewrite branch and handle the responsivity.

fix: ui issue in the rewrite branch

---

README.md

file is removed from the LICENSE.md link
Closes #59

file is removed from the LICENSE.md link

---

index.html
public/index.css

Text inside some section like our community, gaming etc. are too congested. I've added some line height to add some  space between the texts.
Closes #65

Add line-height to improve line spacing between texts

---

index.html
public/index.css

Added hover effect on join community button for visual cue.
Closes #69

fixed-joincommunity button 

---

index.html

feat: crisp

---

.github/workflows/dep-val.yml
package-lock.json
package.json

chore(tools): validate dependencies

---

src/app/_data/team-profiles/Naomi.ts
src/app/home/home.component.ts
src/app/naomi/naomi.component.ts

chore: replace twitter links with mastodon

---

src/styles.css

chore: update cursor link

---

src/app/app.module.ts
src/app/assets.service.spec.ts
src/app/assets.service.ts
src/app/novas/novas.component.spec.ts
src/app/novas/novas.component.ts
src/interfaces/Assets.ts

feat: move to json for file lists

---

src/app/assets.service.ts
src/app/novas/novas.component.html
src/app/novas/novas.component.spec.ts
src/app/novas/novas.component.ts
src/interfaces/Assets.ts
src/interfaces/Pose.ts

feat: use new asset structure

---

src/app/novas/novas.component.html

chore: render data after fetched

---

src/app/novas/novas.component.html

chore: mention melody

---

src/app/home/home.component.ts
src/data/team-profiles/Naomi.ts

chore: update chat link
